# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
defaults: &default
  adapter: postgresql
  host: localhost
  encoding: utf-8
  database: crj_cms_dev
  pool: 5
  # timeout: 5000
  username: <%= ENV["PG_USER"] %>
  password: <%= ENV["PG_PASS"] %>

development:
  adapter: postgresql
  host: localhost
  encoding: utf-8
  database: crj_cms_dev
  host: localhost
  pool: 5
  username: <%= ENV["PG_USER"] %>
  password: <%= ENV["PG_PASS"] %>
  # adapter: postgresql
  # encoding: unicode
  # database: crj_cms_dev
  # pool: 5
  # username: <%= ENV["PG_USER"] %>
  # password: <%= ENV["PG_PASS"] %>

  # socket: /tmp/mysql.sock
  # socket: /var/run/mysqld/mysqld.sock
  # <<: *default
  # database: db/development.sqlite3

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: postgresql
  host: localhost
  encoding: utf-8
  database: crj_cms_test
  pool: 5
  username: <%= ENV["PG_USER"] %>
  password: <%= ENV["PG_PASS"] %>
  # password: <%= ENV["PG_PASS"] %>
  # socket: /tmp/mysql.sock
  # socket: /var/run/mysqld/mysqld.sock

production:
  adapter: postgresql
  host: localhost
  encoding: utf-8
  database: crj_cms_prod
  host: localhost
  pool: 5
  username: <%= ENV["PG_USER"] %>
  password: <%= ENV["PG_PASS"] %>
  # socket: /tmp/mysql.sock
  # socket: /var/run/mysqld/mysqld.sock
